### ISSUE TITLE
[NOT BUG] Updated deprecated opponents

### ISSUE THREAD

**Issue by onurbbr** [flathub/gg.guilded.Guilded#60]
Hello. I have managed to build Guilded using base 24.08. How can I make it pr? Thanks.
![Screenshot_20241015_123835](https://github.com/user-attachments/assets/6758482f-70d1-4841-bb96-c1ebc440edc8)

**Comment by onurbbr** [comment]
I updated `shared-modules` to latest version and added some changes.
```yml
app-id: gg.guilded.Guilded
base: org.electronjs.Electron2.BaseApp
base-version: '24.08' # Use the latest version
runtime: org.freedesktop.Platform
runtime-version: '24.08' # Use the latest version
sdk: org.freedesktop.Sdk
command: guilded
tags:
  - proprietary
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --share=network
  - --device=all
  - --talk-name=org.freedesktop.Notifications
  - --filesystem=xdg-videos:ro
  - --filesystem=xdg-pictures:ro
  - --filesystem=xdg-download
  - --talk-name=org.kde.StatusNotifierWatcher
  - --talk-name=com.canonical.AppMenu.Registrar
  - --talk-name=com.canonical.indicator.application
  - --talk-name=com.canonical.Unity.LauncherEntry
  - --env=XDG_CURRENT_DESKTOP=ubuntu:GNOME
  - --talk-name=org.freedesktop.secrets
modules:
  - name: guilded
    buildsystem: simple
    build-commands:
      - install -Dm644 guilded.png /app/share/icons/hicolor/128x128/apps/${FLATPAK_ID}.png
      - install -Dm644 ${FLATPAK_ID}.desktop /app/share/applications/${FLATPAK_ID}.desktop
      - install -Dm644 gg.guilded.Guilded.appdata.xml /app/share/appdata/gg.guilded.Guilded.appdata.xml
      - install -Dm755 guilded.sh /app/bin/guilded
      - install -Dm755 apply_extra.sh /app/bin/apply_extra
      - install -Dm755 /usr/bin/ar -t /app/bin/
      - install -Dm755 /usr/lib/$(gcc -print-multiarch)/libbfd-*.so -t /app/lib/
      - install -Dm755 /usr/lib/$(gcc -print-multiarch)/libsframe* -t /app/lib/ # Added for compilation, otherwise compilation fails.
      - install -Dm755 /usr/bin/desktop-file-edit -t /app/bin/
    sources:
      - type: extra-data
        filename: Guilded-Linux.deb
        url: https://www.guilded.gg/downloads/Guilded-Linux.deb
        sha256: 3b5ec4574dc99ce6ab1c295088247d684bbb5d42281535af2d5c8b7b74358c1a
        size: 78678630
      - type: file
        path: apply_extra.sh
      - type: file
        path: guilded.sh
      - type: file
        path: gg.guilded.Guilded.appdata.xml
      - type: file
        path: guilded.png
      - type: file
        path: gg.guilded.Guilded.desktop
  - shared-modules/libsecret/libsecret.json
```

I haven't noticed any problems so far.
